CREATE TABLE contacts(ID int(100) NOT NULL AUTO_INCREMENT,NAME VARCHAR(45),VORNAME VARCHAR(45),GEBURTSTAG DATE, PRIMARY KEY ('ID'));
INSERT INTO testtable (ID,NAME,VORNAME,GEBURTSTAG)
    VALUES (1,'Mustermann','Max',CURRENT_DATE),(2,'Müller','Manfred',CURRENT_DATE);

